export const IMPORT_COPY = {
    es: {
        title: "Importar Horario",
        subtitle: "Restaura respaldos JSON y revisa el archivo antes de cargarlo.",
        drop: "Arrastra tu respaldo aquí",
        browse: "o haz clic para seleccionar un archivo",
        supported: "Formato soportado: .json",
        privacy: "La importación ocurre localmente en tu navegador.",
        reviewTitle: "Revisar archivo seleccionado",
        reviewNote: "Confirma que este es el respaldo correcto antes de importarlo.",
        cancel: "Cancelar",
        confirm: "Confirmar Importación",
        done: "Importación completada",
        doneDesc: "Tu respaldo fue procesado correctamente.",
        importAnother: "Importar otro archivo",
        chooseFile: "Seleccionar archivo",
        invalidFile: "El archivo no es un respaldo válido",
        restoreSuccess: "Respaldo restaurado con éxito",
        missingSettings: "El respaldo no contiene configuración.",
        missingTasks: "El respaldo no contiene tareas.",

        imageImportTitle: "Importar horario desde imagen",
        imageImportSubtitle:
            "Sube una captura o foto de tu horario. Revisa los datos antes de guardarlos.",
        imageImportWarningTitle: "Importante: el OCR puede cometer errores.",
        imageImportWarningDescription:
            "Verifica los días, horas y nombres de las actividades antes de importar. El sistema puede leer mal números, letras o posiciones dentro de la imagen.",
        imageScheduleLabel: "Imagen del horario",
        imageDrop: "Arrastra una imagen aquí",
        imageBrowse: "o haz clic para seleccionar una captura de tu horario",
        selectedFile: "Archivo seleccionado",
        invalidImage: "Selecciona una imagen válida.",
        processImage: "Procesar con OCR",
        processingImage: "Procesando imagen...",
        preparingOcr: "Preparando OCR...",
        ocrEmptyText: "No se detectó texto en la imagen.",
        ocrProcessError: "No se pudo procesar la imagen con OCR.",
        detectedTextSummary: "Ver / corregir texto detectado",
        detectedTextPlaceholder: "Aquí aparecerá el texto reconocido por OCR...",
        detectActivities: "Detectar actividades",
        noDetectedActivities:
            "No se detectaron actividades. Revisa que el texto tenga día y hora.",
        detectedActivitiesMessage:
            "actividad(es) detectada(s). Revisa días y horas antes de importar.",
        reviewDetectedText:
            "Revisa el texto detectado y presiona “Detectar actividades”.",
        detectedActivitiesTitle: "Actividades detectadas",
        results: "resultado",
        resultsPlural: "resultados",
        day: "Día",
        start: "Inicio",
        end: "Fin",
        activity: "Actividad",
        action: "Acción",
        remove: "Quitar",
        saving: "Guardando...",
        confirmDetectedActivities: "Confirmar e importar actividades revisadas",
        untitledActivity: "Actividad sin nombre",
    },

    en: {
        title: "Import Schedule",
        subtitle: "Restore JSON backups and review the file before loading it.",
        drop: "Drop your backup here",
        browse: "or click to choose a file",
        supported: "Supported format: .json",
        privacy: "Import runs locally in your browser.",
        reviewTitle: "Review selected file",
        reviewNote: "Confirm this is the correct backup before importing.",
        cancel: "Cancel",
        confirm: "Confirm Import",
        done: "Import completed",
        doneDesc: "Your backup was processed successfully.",
        importAnother: "Import another file",
        chooseFile: "Choose file",
        invalidFile: "Invalid backup file",
        restoreSuccess: "Backup restored successfully",
        missingSettings: "The backup does not include settings.",
        missingTasks: "The backup does not include tasks.",

        imageImportTitle: "Import schedule from image",
        imageImportSubtitle:
            "Upload a screenshot or photo of your schedule. Review the data before saving.",
        imageImportWarningTitle: "Important: OCR can make mistakes.",
        imageImportWarningDescription:
            "Verify days, times, and activity names before importing. The system can misread numbers, letters, or positions inside the image.",
        imageScheduleLabel: "Schedule image",
        imageDrop: "Drop an image here",
        imageBrowse: "or click to choose a schedule screenshot",
        selectedFile: "Selected file",
        invalidImage: "Choose a valid image.",
        processImage: "Process with OCR",
        processingImage: "Processing image...",
        preparingOcr: "Preparing OCR...",
        ocrEmptyText: "No text was detected in the image.",
        ocrProcessError: "The image could not be processed with OCR.",
        detectedTextSummary: "View / correct detected text",
        detectedTextPlaceholder: "OCR-recognized text will appear here...",
        detectActivities: "Detect activities",
        noDetectedActivities:
            "No activities were detected. Check that the text includes day and time.",
        detectedActivitiesMessage:
            "activity item(s) detected. Review days and times before importing.",
        reviewDetectedText: "Review the detected text and press “Detect activities”.",
        detectedActivitiesTitle: "Detected activities",
        results: "result",
        resultsPlural: "results",
        day: "Day",
        start: "Start",
        end: "End",
        activity: "Activity",
        action: "Action",
        remove: "Remove",
        saving: "Saving...",
        confirmDetectedActivities: "Confirm and import reviewed activities",
        untitledActivity: "Untitled activity",
    },
} as const;

export type ImportLanguage = keyof typeof IMPORT_COPY;

export function getImportCopy(lang: string) {
    return IMPORT_COPY[lang as ImportLanguage] ?? IMPORT_COPY.es;
}